version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_todo_pod
      POSTGRES_PASSWORD: "Pl8cBYYbZWxljMiaROmu8yXgaSkb6jE_"
    volumes:
      - my_todo_pod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "4ECrKxmNgjiJQyqR0fKl98je0uPpZkkz"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  my_todo_pod_data:
